include:
  - project: 'scimedsolutions/technical-knowledge-base'
    file: '/ci/mysql/v1.yml'

image: registry.gitlab.com/scimedsolutions/howesgrocery/howes_grocery_researcher_portal:0.0.16

rspec:
  before_script:
    - cp config/database.yml.example config/database.yml
    - bundle install -j $(nproc) --path /vendor/ruby --without development production --deployment
    - yarn install
    - yarn build
    - bundle exec rake db:create db:migrate

