inherit_from:
  - https://raw.githubusercontent.com/SciMed/style-guide/master/.rubocop.yml

AllCops:
  Exclude:
    - '**/bin/**/*'
    - '**/config/**/*'
    - '**/node_modules/**/*'
    - '**/script/**/*'
    - '**/spec/test_app/**/*'
    - '**/*.gemspec'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
    - '**/Vagrantfile'
    - '**/db/schema.rb'
    - '**/lib/scripts/**/*'
  TargetRubyVersion: 3.1
  TargetRailsVersion: 6.1 

Layout/CaseIndentation:
  IndentOneStep: true
Layout/ClassStructure:
  Enabled: true
Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Layout/LineLength:
  Exclude:
    - '**/bin/**/*'
    - '**/config/**/*'
    - '**/db/migrate/**/*'
    - '**/spec/**/*'
  Max: 80
Layout/MultilineHashKeyLineBreaks:
  Enabled: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/SpaceAroundMethodCallOperator:
  Enabled: true
Layout/SpaceBeforeFirstArg:
  Exclude:
    - '**/spec/factories/**/*'

# Disabled for specs to allow following pattern:
# expect { Foo.create }.to change { Foo.count }
Lint/AmbiguousBlockAssociation:
  Exclude:
    - '**/spec/**/*'
Lint/DeprecatedOpenSSLConstant:
  Enabled: true
Lint/DuplicateElsifCondition:
  Enabled: true
Lint/MixedRegexpCaptureTypes:
  Enabled: true
Lint/RaiseException:
  Enabled: true
Lint/StructNewOverride:
  Enabled: true

Metrics/AbcSize:
  Exclude:
    - '**/db/migrate/**/*'
Metrics/BlockLength:
  Exclude:
    - '**/config/**/*'
    - '**/helpers/**/*'
    - '**/db/**/*'
    - '**/spec/**/*'
    - '**/lib/**/*'
Metrics/ClassLength:
  Exclude:
    - 'app/controllers/conditions_controller.rb'
    - 'app/models/condition.rb'
    - 'app/services/cart.rb'
    - 'app/services/condition_manager.rb'
    - 'app/services/csv_file_managers/sorting.rb'
    - 'app/services/equation.rb'
    - 'app/services/product_url_manager.rb'
    - 'app/services/product_variable.rb'
    - '**/db/migrate/**/*'
    - '**/db/seeds/**/*'
Metrics/CyclomaticComplexity:
  Max: 5
Metrics/MethodLength:
  Max: 15
  Exclude:
    - '**/db/**/*'
Metrics/ModuleLength:
  Exclude:
    - '**/db/seeds/**/*'
Metrics/PerceivedComplexity:
  Max: 5

Naming/AccessorMethodName:
  Exclude:
    - '**/app/controllers/**/*'
Naming/BlockForwarding:
  Enabled: false
Naming/BlockParameterName:
  AllowedNames:
    - id
    - x
    - y
    - k
    - v
    - _
Naming/MethodParameterName:
  AllowedNames:
    - id
    - x
    - y
    - _

Performance/AncestorsInclude:
  Enabled: false
Performance/BigDecimalWithNumericArgument:
  Enabled: true
# `foo.downcase == bar.downcase` is more readable than
# `foo.casecmp(bar).zero?`
Performance/Casecmp:
  Enabled: false
Performance/CaseWhenSplat:
  Enabled: true
Performance/IoReadlines:
  Enabled: true
Performance/RedundantSortBlock:
  Enabled: true
Performance/RedundantStringChars:
  Enabled: true
Performance/ReverseFirst:
  Enabled: true
Performance/SortReverse:
  Enabled: true
Performance/Squeeze:
  Enabled: true
Performance/StringInclude:
  Enabled: true

Rails/ActiveRecordCallbacksOrder:
  Enabled: true
Rails/Blank:
  NilOrEmpty: false
  UnlessPresent: false
Rails/DefaultScope:
  Enabled: true
Rails/FilePath:
  EnforcedStyle: slashes
Rails/FindById:
  Enabled: true
# Keyword arguments aren't functionally equivalent to positional arguments.
# Using keyword arguments in controller specs makes the param keys strings and
# not symbols, even if adding `.with_indifferent_access`.
Rails/HttpPositionalArguments:
  Enabled: false
Rails/Inquiry:
  Enabled: true
Rails/MailerName:
  Enabled: true
Rails/MatchRoute:
  Enabled: true
Rails/NegateInclude:
  Enabled: true
# There are often no reasonable defaults for not null columns
Rails/NotNullColumn:
  Enabled: false
Rails/Output:
  Exclude:
    - '**/db/seeds.rb'
    - '**/lib/tasks/**/*'
Rails/Pluck:
  Enabled: true
Rails/PluckId:
  Enabled: false
Rails/PluckInWhere:
  Enabled: true
Rails/RenderInline:
  Enabled: true
Rails/RenderPlainText:
  Enabled: true
Rails/ShortI18n:
  Enabled: false
Rails/UniqBeforePluck:
  EnforcedStyle: aggressive
Rails/WhereExists:
  Enabled: true

# Prefer eql
RSpec/BeEql:
  Enabled: false
RSpec/BeforeAfterAll:
  Exclude:
    - '**/spec/models/power_spec.rb'
    - '**/spec/models/powers/*'
RSpec/ContextWording:
  Prefixes:
    - by
    - when
    - with
    - without
# No class to describe for feature tests
RSpec/DescribeClass:
  Exclude:
    - '**/spec/features/**/*'
RSpec/EmptyLineAfterExample:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/ExpectChange:
  EnforcedStyle: block
RSpec/ImplicitSubject:
  Enabled: false
RSpec/InstanceVariable:
  Exclude:
    - '**/spec/models/power_spec.rb'
    - '**/spec/models/powers/*'
RSpec/LeadingSubject:
  Enabled: false
RSpec/LetSetup:
  Exclude:
    - '**/spec/features/**/*'
RSpec/MessageChain:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/ReturnFromStub:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false

Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/AccessorGrouping:
  Enabled: true
Style/ArrayCoercion:
  Enabled: true
Style/AutoResourceCleanup:
  Enabled: true
Style/BisectedAttrAccessor:
  Enabled: true
Style/CaseLikeIf:
  Enabled: false
Style/CollectionMethods:
  Enabled: true
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false
Style/DateTime:
  Enabled: true
Style/Documentation:
  Exclude:
    - '**/controllers/**/*'
    - '**/db/**/*'
    - '**/app/helpers/application_helper.rb'
    - '**/app/mailers/application_mailer.rb'
    - '**/app/models/application_record.rb'
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/ExponentialNotation:
  Enabled: true
  EnforcedStyle: scientific
Style/FormatStringToken:
  Enabled: false
Style/HashAsLastArrayItem:
  Enabled: false
Style/HashEachMethods:
  Enabled: true
Style/HashLikeCase:
  Enabled: true
Style/HashSyntax:
  Enabled: false
Style/HashTransformKeys:
  Enabled: true
Style/HashTransformValues:
  Enabled: true
Style/IpAddresses:
  Enabled: true
Style/Lambda:
  EnforcedStyle: literal
Style/NumericPredicate:
  Enabled: false
Style/OpenStructUse:
  Enabled: false
Style/OptionHash:
  Enabled: true
Style/RedundantAssignment:
  Enabled: true
Style/RedundantFetchBlock:
  Enabled: true
Style/RedundantFileExtensionInRequire:
  Enabled: true
Style/RedundantRegexpCharacterClass:
  Enabled: true
Style/RedundantRegexpEscape:
  Enabled: true
Style/Send:
  Enabled: true
# Prevents self-documentation
Style/SingleLineBlockParams:
  Enabled: false
Style/SlicingWithRange:
  Enabled: false
Style/StringMethods:
  Enabled: true

# Defaults; may make sense to change for specific projects
Rails/SaveBang:
  Enabled: true
Rails/UniqueValidationWithoutIndex:
  Enabled: false

Style/RedundantBegin:
  Enabled: true
Style/ZeroLengthPredicate:
  Enabled: true

# project-specific changes:
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/MultilineMethodArgumentLineBreaks:
  Enabled: false
Lint/NumberConversion:
  Enabled: false
Naming/VariableNumber:
  Enabled: false
Rails/BulkChangeTable:
  Enabled: false
Rails/UnknownEnv:
  Environments:
    - development
    - test
    - staging
    - production
RSpec/MessageSpies:
  Enabled: false
RSpec/MultipleMemoizedHelpers:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
