require: rubocop-rspec

AllCops:
  Exclude:
    - '**/bin/**/*'
    - '**/public/**/*'
    - '**/config/**/*'
    - '**/script/**/*'
    - '**/vendor/**/*'
    - '**/public/**/*'
    - '**/node_modules/**/*'
    - '**/spec/rails_helper.rb'
    - '**/spec/spec_helper.rb'
    - '**/test/test_helper.rb'
    - '**/Gemfile'
    - '**/Guardfile'
    - '**/Rakefile'
    - '**/Vagrantfile'
    - '**/*.gemspec'
    - '**/db/schema.rb'
  DisplayCopNames: true
  TargetRubyVersion: 2.4.2
  TargetRailsVersion: 5.2

Layout/FirstArrayElementLineBreak:
  Enabled: true
Layout/FirstHashElementLineBreak:
  Enabled: true
Layout/FirstMethodArgumentLineBreak:
  Enabled: true
Layout/FirstMethodParameterLineBreak:
  Enabled: true
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/MultilineOperationIndentation:
  EnforcedStyle: indented
Layout/SpaceBeforeFirstArg:
  Exclude:
    - '**/spec/factories/**'

Lint/AmbiguousBlockAssociation:
  Exclude:
    - '**/spec/**/*'

Metrics/AbcSize:
  Exclude:
    - '**/db/migrate/**/*'
Metrics/BlockLength:
  Exclude:
    - '**/config/**/*'
    - '**/helpers/**/*'
    - '**/db/migrate/**/*'
    - '**/spec/**/*'

Metrics/LineLength:
  Exclude:
    - '**/bin/**/*'
    - '**/config/**/*'
    - '**/db/migrate/**/*'
    - '**/spec/**/*'
  Max: 80
Metrics/MethodLength:
  Max: 15
  Exclude:
    - '**/db/migrate/**/*'

Naming/AccessorMethodName:
  Enabled: false
Naming/VariableNumber:
  EnforcedStyle: snake_case

# `foo.downcase == bar.downcase` is more readable than
# `foo.casecmp(bar).zero?`
Performance/Casecmp:
  Enabled: false

Rails:
  Enabled: true
Rails/Blank:
  NilOrEmpty: false
  UnlessPresent: false
# Keyword arguments aren't functionally equivalent to positional arguments.
# Using keyword arguments in controller specs makes the param keys strings and
# not symbols, even if adding `.with_indifferent_access`.
Rails/HttpPositionalArguments:
  Enabled: false
# There are often no reasonable defaults for not null columns
Rails/NotNullColumn:
  Enabled: false
Rails/Output:
  Exclude:
    - '**/db/seeds.rb'
    - '**/lib/tasks/**/*'
Rails/SaveBang:
  Enabled: true
Rails/UniqBeforePluck:
  EnforcedStyle: aggressive

# No class to describe for feature tests
RSpec/DescribeClass:
  Exclude:
    - '**/spec/features/**/*'
RSpec/ExampleLength:
  Enabled: false
RSpec/LeadingSubject:
  Enabled: false
RSpec/MessageChain:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/NamedSubject:
  Enabled: false
RSpec/NestedGroups:
  Enabled: false
RSpec/SubjectStub:
  Enabled: false
Rails/ApplicationRecord:
    Enabled: false
Rails/Blank:
  NilOrEmpty: false
  UnlessPresent: false
# Keyword arguments aren't functionally equivalent to positional arguments.
# Using keyword arguments in controller specs makes the param keys strings and
# not symbols, even if adding `.with_indifferent_access`.
Rails/HttpPositionalArguments:
  Enabled: false
# There are often no reasonable defaults for not null columns
Rails/NotNullColumn:
  Enabled: false
Rails/Output:
  Exclude:
    - '**/db/seeds.rb'
    - '**/lib/tasks/**/*'
Rails/UniqBeforePluck:
  EnforcedStyle: aggressive
RSpec/ReturnFromStub:
  Enabled: false
Style/AccessModifierDeclarations:
  EnforcedStyle: inline
Style/AutoResourceCleanup:
  Enabled: true
# We prefer `alias_method`
Style/CollectionMethods:
  Enabled: true
Style/ConditionalAssignment:
  EnforcedStyle: assign_inside_condition
  IncludeTernaryExpressions: false
Style/Documentation:
  Enabled: false
Style/EmptyMethod:
  EnforcedStyle: expanded
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/Lambda:
  EnforcedStyle: literal
Style/NumericPredicate:
  Enabled: false
Style/OptionHash:
  Enabled: true
Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%i': '()'
    '%I': '()'
    '%w': '()'
    '%W': '()'
Style/SafeNavigation:
  Enabled: false
Style/Send:
  Enabled: true
Style/SingleLineBlockParams:
  Enabled: false
Style/StringMethods:
  Enabled: true
Style/StringHashKeys:
  Enabled: true
