---
- block:
  - name: Download
    get_url:
      url: https://dl.yarnpkg.com/rpm/yarn.repo
      dest: /etc/yum.repos.d/yarn.repo
  - name: Install
    yum:
        name: yarn
        state: present
  become: yes
