---
## USAGE INSTRUCTIONS ##
# Make sure you have this file: ~/.ansible/vault/scimed.txt
# Get it from a devops person if you don't have them.
# Install the roles in the local roles directory for this project:
# $> ansible-galaxy install -r requirements.yml --roles-path ./roles
#
# Run the playbook:
# $> ansible-playbook staging.yml
#
# If you can't login to the server, please make sure the server
# is correctly set up and authorized with your SSH public key.
- name: Howes Grocery
  hosts: staging
  vars_files:
    - group_vars/staging/vars.yml
    - group_vars/staging/vault.yml

  tasks:
    - block:
      - name: mkswap
        command: mkswap /dev/xvdb
        when: ansible_swaptotal_mb < 1
      - name: swapon
        command: swapon /dev/xvdb
        when: ansible_swaptotal_mb < 1
      - name: write to fstab
        mount:
          path: none
          src: /dev/xvdb
          fstype: swap
          opts: sw
          state: present
      become: True
    - block:
      - name: Install MySQL client
        yum:
          name: "{{ item }}"
          state: present
        with_items:
          - mysql
          - mysql-devel
      become: true


  roles:
    - scimed.common
    - scimed.rbenv
    - scimed.capistrano
    - scimed.passenger
    - scimed.apache
    - scimed.rails
    - yarn
    - letsencrypt
